# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
